var config = {
  style: "mapbox://styles/shogohirasawa/clcecwncv000m14mnlel1k7sh",
  accessToken:
    "pk.eyJ1Ijoic2hvZ29oaXJhc2F3YSIsImEiOiJjazFhbzVrMG0yNmxjM2xuaTBmM3h0dW4wIn0.Bxjy09jy_cwOQVexF1xBfg",
  showMarkers: false,
  theme: "light",
  use3dTerrain: false,
  //   title: "Mapbox Root",
  //   subtitle: "Mapboxの遍歴をたどったストーリーテリング",
  //   byline: "By a Digital Storyteller",
  //   footer: "Source: source citations, etc.",
  chapters: [
    {
      id: "1",
      alignment: "right",
      hidden: false,
      title: "地図のない世界に光を",
      image:
        "https://shogohirasawa.github.io/Mapbox_rootmap/image/origins/Mapbox_origins-Monitoring_fair_elections_in_Afghanistan.jpeg",
      description:
        "パキスタンの洪水マップやアフガニスタンの選挙マップの作成など、限られたデジタル環境下でも大量のデータをマッピングできるツールとして開発されたのが「Mapbox」でした。発展途上国に限らず、世界中の様々な分野で高パフォーマンスを発揮する地図プラットフォームがここに誕生しました。",
      location: {
        center: [65.68784, 34.32715],
        zoom: 5.41,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    {
      id: "2",
      alignment: "right",
      hidden: false,
      title: "2010年 Mapbox Inc.設立",
      image:
        "https://shogohirasawa.github.io/Mapbox_rootmap/image/origins/Mapbox_origins-Development_Seed_circa_2012.jpg",
      description: "ワシントンDCの14番街の路地裏にあるガレージでスタート",
      location: {
        center: [-77.04014, 38.89518],
        zoom: 10.68,
        pitch: 60.0,
        bearing: -36.8,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    {
      id: "3",
      alignment: "right",
      hidden: false,
      title: "2015年 グローバル企業へ",
      image:
        "https://images.unsplash.com/photo-1516738901171-8eb4fc13bd20?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
      description: "世界各地にオフィスを持つ500人以上の優秀なチームに成長",
      location: {
        center: [-1.12782, 31.55374],
        zoom: 1.38,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    {
      id: "4",
      alignment: "right",
      hidden: false,
      title: "アメリカ ワシントンDC office",
      image:
        "https://shogohirasawa.github.io/Mapbox_rootmap/image/offices/washington-dc(1).jpg",
      location: {
        center: [-77.03859, 38.88175],
        zoom: 11.0,
        pitch: 60,
        bearing: 38.01,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },

    {
      id: "5",
      alignment: "right",
      hidden: false,
      title: "アメリカ サンフランシスコ office",
      image:
        "https://shogohirasawa.github.io/Mapbox_rootmap/image/offices/san-francisco-0-1200x800.jpg",
      // description: "",
      location: {
        center: [-122.43945, 37.75321],
        zoom: 10.28,
        pitch: 43.0,
        bearing: 30.0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    {
      id: "6",
      alignment: "right",
      hidden: false,
      title: "フィンランド ヘルシンキ office",
      image:
        "https://shogohirasawa.github.io/Mapbox_rootmap/image/offices/Helsinki.jpg",
      // description: "",
      location: {
        center: [24.93331, 60.18783],
        zoom: 10.12,
        pitch: 59.0,
        bearing: 20.0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    // {
    //   id: "7",
    //   alignment: "left",
    //   hidden: false,
    //   title: "ミンスク office",
    //   image:
    //     "https://shogohirasawa.github.io/Mapbox_rootmap/image/offices/minsk-IMG_3918.jpg",
    //   // description: "",
    //   location: {
    //     center: [27.58657, 53.88578],
    //     zoom: 10.68,
    //     pitch: 41.0,
    //     bearing: 0.0,
    //   },
    //   mapAnimation: "flyTo",
    //   rotateAnimation: false,
    //   callback: "",
    //   onChapterEnter: [],
    //   onChapterExit: [],
    // },
    {
      id: "8",
      alignment: "right",
      hidden: false,
      title: "2020年3月10日 マップボックス・ジャパン設立",
      description:
        '<div class="vid_contents"> <video autoplay loop class="vid_main" src="https://shogohirasawa.github.io/Mapbox_rootmap/video/MapboxJapanOfficeTour.mp4" controls loop playsinline muted></video> </div><p>Mapbox Inc.とソフトバンク株式会社が合同出資し、「マップボックス・ジャパン合同会社」を2020年3月10日に設立。CEO高田を中心に日本の新しい地図プラットフォームに挑戦。<p>',
      location: {
        center: [139.77084, 35.68273],
        zoom: 8.8,
        pitch: 41.0,
        bearing: 0.0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    {
      id: "9",
      alignment: "right",
      hidden: false,
      title: "2021年7月 日本独自の地図広告プロダクト「Mapbox広告」をリリース",
      image:
        "https://shogohirasawa.github.io/Mapbox_rootmap/image/Japan/map_ad_2.png",
      description:
        "マップボックス・ジャパンから地図広告プロダクト「Mapbox広告」をリリース。Web地図の新しい広告技術を日本から発信",
      location: {
        center: [139.7501, 35.66992],
        zoom: 15.08,
        pitch: 55.0,
        bearing: 0.0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    {
      id: "10",
      alignment: "right",
      hidden: false,
      title: "ストーリーテリングについて",
      image:
        "https://shogohirasawa.github.io/Mapbox_rootmap/image/origins/mapbox_image.png",
      description:
        '<p>このルーツマップはMapboxのストーリーテリングのテンプレートを利用して作成しました。<br>ストーリーテリングについて詳しくは<a href="https://www.mapbox.jp/blog/interactive-storytelling-3d-maps-with-mapbox-gl-js-v2">こちら</a></p>',
      location: {
        center: [139.7501, 35.66992],
        zoom: 15.08,
        pitch: 55.0,
        bearing: 0.0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
  ],
};
