var config = {
  style: "mapbox://styles/mapbox/streets-v11",
  accessToken:
    "pk.eyJ1Ijoic2hvZ29oaXJhc2F3YSIsImEiOiJja3Zsd3kxMzk1NDV1MnFvazN4OHI5OWN4In0.I-kllSJi19LcGRCHV4M5aw",
  showMarkers: true,
  markerColor: "#3FB1CE",
  theme: "light",
  use3dTerrain: false,
  //   title: "Mapbox Root",
  //   subtitle: "Mapboxの遍歴をたどったストーリーテリング",
  //   byline: "By a Digital Storyteller",
  //   footer: "Source: source citations, etc.",
  chapters: [
    {
      id: "1",
      alignment: "left",
      hidden: false,
      title: "地図のない世界に光を",
      image:
        "https://shogohirasawa.github.io/Mapbox_rootmap/image/origins/Mapbox_origins-Monitoring_fair_elections_in_Afghanistan.jpeg",
      description:
        "Eric Gundersenによって創設されたMapbox。Mapboxは地図で様々なNGOの支援を行うために作られました。パキスタンの洪水マップやアフガニスタンの選挙マップの作成など、限られたデジタル環境下でも大量のデータをマッピングできるツールとして活用されていました。発展途上国に限らず世界中の様々な分野で高パフォーマンスを発揮する地図プラットフォームがここに誕生しました。",
      location: {
        center: [65.68784, 34.32715],
        zoom: 5.41,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    {
      id: "2",
      alignment: "right",
      hidden: false,
      title: "2010年 Mapbox Inc.設立",
      image:
        "https://shogohirasawa.github.io/Mapbox_rootmap/image/origins/Mapbox_origins-Development_Seed_circa_2012.jpg",
      description: "ワシントンDCの14番街の路地裏にあるガレージでスタート",
      location: {
        center: [-77.04014, 38.89518],
        zoom: 10.68,
        pitch: 60.0,
        bearing: -36.8,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    {
      id: "3",
      alignment: "right",
      hidden: false,
      title: "2010年 Mapbox Inc.設立",
      image:
        "https://shogohirasawa.github.io/Mapbox_rootmap/image/origins/Mapbox_origins-Development_Seed_circa_2012.jpg",
      description: "ワシントンDCの14番街の路地裏にあるガレージでスタート",
      location: {
        center: [-77.04014, 38.89518],
        zoom: 10.68,
        pitch: 60.0,
        bearing: -36.8,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
  ],
};
